### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by VegaDeftwing** [zezic/ZZC#37]
The project is GPL V3'd, but what is the licence/copyright on the graphics (knobs, buttons, sliders, module art)? I'm looking at creating a set of alternative SVGs for other 3rd party modules what match those from ZZC.

**Comment by zezic** [comment]
@VegaDeftwing I just added a mention of license of panel graphics to LICENSE.txt, thank you for asking this question. They are not under GPL V3.
I will kindly give you permission to use ZZC graphics in a publicly available project (such as a set of alternative SVGs for some other VCV modules) after reviewing the panel layouts. The ergonomic of panel layout of a module where you plan to use graphics is a main point of this question. For some existing modules it's hard to make panel look nice without changing its source code because of non-pleasant layout of controls.
So, I need to review panels to make sure that ZZC graphics are looking decently with new layouts. Please, send examples of new panels to this thread or to my email zezic51@yandex.ru and I will give a response shortly. There is even a chance that I will provide the additional graphics for missing widgets.

**Comment by VegaDeftwing** [comment]
Awesome, It'll be a bit before I have enough done for it to make sense. Unfortunately the only way to replace some of the knobs/ports on a lot of modules without recompiling is to change the svgs in the stock component library. I tried a few things just to make sure everything I wanted to do was possible- these are in no way representative of what I'd consider final versions: 
![DeepinScreenshot_select-area_20190603001251](https://user-images.githubusercontent.com/11283620/58817490-751da380-85f1-11e9-9d49-6f4901f8c668.png)
but you can see that in order to replace the sockets without recompilation I've had to replace them on everything

**Comment by zezic** [comment]
Ohh, I'm not sure that remixing the graphics of Fundamental modules is a good idea. They are © 2018 by Grayscale and licensed under CC BY-NC-ND 4.0.

Also, by coincidence there was a discussion about excessive similarity of ZZC modules design to design of Fundamental modules. I had to change fonts to make them not feel too much as "plagiarism". So your intention of giving them ZZC-style can become a risky operation in such hot situation :)

In the end, all official VCV modules are having very nice design already. Also you can notice that it's almost impossible to properly apply curved knobs without modifying the source code because of offsets and, as you already have said, it's hard to do because of the replacement of default port graphics which affects all other modules.

**Comment by VegaDeftwing** [comment]
The original graphics are C grayscale, but so long as I change everything,
not using thu original svg at all it should be fine?

**Comment by zezic** [comment]
Theoretically, it should be legal. But I don't think that you will get a positive feedback from authors of modules, especially from authors of Fundamental. And keep in mind that to make such redesign package to not break something you will have to provide skins for all modules (free and paid) which use core graphics in their components (this is quite large number) and to update it when some new module come out.

Please, forgive me, but It looks like in current situation it's almost impossible to support such skin pack easily, because eventually a new module which uses core graphics will come out and light ZZC-styled ports will appear on it (you know, they are looking pretty bad on a light background).

**Comment by VegaDeftwing** [comment]
Yeah, I think youre right. Ill just start from scratch then. Thanks anyway
:)
