### ISSUE TITLE
Phaseque 2.0 Bump

### ISSUE THREAD

**Issue by VegaDeftwing** [zezic/ZZC#97]
Hope things have been well for you, realized it's been the better part of a year since anyone bumped this.

**Comment by zezic** [comment]
Thanks for bump... It seems, it's hard to concentrate on the Phaseque codebase for me atm, so, as you asked already, here is the source: https://github.com/zezic/ZZC-Phaseque

I think, since community is able to directly participate in development we should change the license of Phaseque. After it become 100% compatible with Rack 2.0 I (hope) I can contact Andrew to adjust plugin visibility in VCV library, set it as free (remove price) and keep its slug for compatibility with existing patches.
